name: flutter_deepar_example
description: Demonstrates how to use the flutter_deepar plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  path_provider: ^2.0.2
  video_player: ^2.1.6
  permission_handler: ^9.2.0
  photo_manager: ^2.0.6

dependency_overrides:
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_deepar:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/deepar_masks/
#       - assets/deepar_masks/aviators
#       - assets/deepar_masks/bigmouth
#       - assets/deepar_masks/bleachbypass
#       - assets/deepar_masks/blizzard
#       - assets/deepar_masks/dalmatian
#       - assets/deepar_masks/drawingmanga
#       - assets/deepar_masks/fatify
#       - assets/deepar_masks/filmcolorperfection
#       - assets/deepar_masks/fire
#       - assets/deepar_masks/flowers
#       - assets/deepar_masks/grumpycat
#       - assets/deepar_masks/heart
#       - assets/deepar_masks/kanye
#       - assets/deepar_masks/koala
#       - assets/deepar_masks/lion
#       - assets/deepar_masks/mudMask
#       - assets/deepar_masks/obama
#       - assets/deepar_masks/pug
#       - assets/deepar_masks/rain
#       - assets/deepar_masks/realvhs
#       - assets/deepar_masks/sepia
#       - assets/deepar_masks/slash
#       - assets/deepar_masks/sleepingmask
#       - assets/deepar_masks/smallface
#       - assets/deepar_masks/teddycigar
#       - assets/deepar_masks/tripleface
#       - assets/deepar_masks/tv80
#       - assets/deepar_masks/twistedface
#       - assets/deepar_masks/background_segmentation
#       - assets/deepar_masks/hair_segmentation

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
